name: Deploy to Raspberry Pi

on:
  workflow_dispatch:
  workflow_run:
      workflows: ["publish-to-pypi.yml"] 
      types: [completed]

      branches: [main] 
permissions:
  id-token: write # This is required for the tailscale action to request a JWT from GitHub

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Tailscale
        uses: tailscale/github-action@v2
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci
      
      - name: SSH to Raspberry Pi and install package from PyPI
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.PI_TAILSCALE_IP }}
          username: ${{ secrets.PI_USER }}
          password: ${{ secrets.PI_PASSWORD }}
          script: |
            python3 -m pip install --upgrade martinaPI
            #martinapi.sh >> martina-$(date +%Y-%m-%d).log 2>&1
